### PR TITLE
Added link as requested

### PR DESCRIPTION
**Pull request by divyasunny98**
I have added a link as a beginner from _VJCET_ solving issue no #1 

@krupamaria @liya-katti

### CODE REVIEW

**Comment by de-sh** [comment]
Please mention the issue #1

**Comment by simijames** [comment]
my first attempt

**Comment by de-sh** [comment]
> my first attempt

Awesome @simijames and this is a very good PR @divyasunny98. Accepted!

**Comment by de-sh** [comment]
Hello team, as I had promised here is your prize, I hereby invite you to be members of the LINK git organization!

Start by making changes to your git profile, add a Profile Picture and also write a cool bio about yourself!

**Comment by de-sh** [comment]
Hello, there has been no response to this. There is a new competition coming up! Are you a technical writer?

Can you write awesome content?

Join us on the journey to WiES as we help you bring out the technical builder in you. You can start out by documenting your experiences with learning GitHub. Are you interested?

**Pull request merged**
